---
name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update requirements.txt
        uses: ryan-rozario/pipreqs-action@v2.7.0
        with:
          PROJECT_PATH: .
          REQUIREMENT_PATH: ./requirements.txt
